sonar.projectKey=Pawarasasmina_EventHub---CTSE-Assignment
sonar.organization=pawarasasmina
sonar.projectName=EventHub
sonar.sourceEncoding=UTF-8

sonar.sources=gateway/src,services/auth-service/src,services/event-service/src,services/booking-service/src,services/notification-service/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.tmp_*/**,frontend/src/main.jsx
sonar.coverage.exclusions=frontend/src/**,**/src/docs/**,**/src/routes/**,**/src/middleware/**,**/src/models/**,**/src/server.js,**/src/app.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
