sonar.projectKey=REPLACE_WITH_YOUR_SONARCLOUD_PROJECT_KEY
sonar.organization=REPLACE_WITH_YOUR_SONARCLOUD_ORGANIZATION
sonar.projectName=EventHub
sonar.sourceEncoding=UTF-8

sonar.sources=gateway/src,services/auth-service/src,services/event-service/src,services/booking-service/src,services/notification-service/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.tmp_*/**,frontend/src/main.jsx
