sonar.projectKey=Pawarasasmina_EventHub-booking-service
sonar.organization=pawarasasmina
sonar.projectName=EventHub Booking Service
sonar.sourceEncoding=UTF-8

sonar.sources=services/booking-service/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.tmp_*/**
sonar.coverage.exclusions=**/src/docs/**,**/src/routes/**,**/src/middleware/**,**/src/models/**,**/src/server.js,**/src/app.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
