sonar.projectKey=Pawarasasmina_EventHub-event-service
sonar.organization=pawarasasmina
sonar.projectName=EventHub Event Service
sonar.sourceEncoding=UTF-8

sonar.sources=services/event-service/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.tmp_*/**
sonar.coverage.exclusions=services/event-service/src/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
